name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update
    - run: sudo apt install -y python3-pytest python3-pip python3-selenium jq chromium-driver 
    - run: pytest-3 test.py
